### PR TITLE
something stating that the GUI release is under development will be nice

### PR DESCRIPTION
**Pull request by ghost**
title says it all

### CODE REVIEW

**Comment by anf** [comment]
I don't think that header really fits there, but a small note would be nice, however, this is not something to create a pr on, just an issue would be more than enough. I'm thinking a small p tag would be better within the latest releases header.

**Comment by ghost** [comment]
okau

> I don't think that header really fits there, but a small note would be nice, however, this is not something to create a pr on, just an issue would be more than enough. I'm thinking a small p tag would be better within the latest releases header.

Alright, I haven't _really_ used github that much, I'll keep this in mind the next time

**Comment by anf** [comment]
Alrighty.

**Comment by tomlin7** [comment]
yes a tag would be nice

**Pull request closed without merging**
